namespace CataProject_Script_Generator
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Drawing;
    using System.IO;
    using System.Text;
    using System.Windows.Forms;
    partial class Form1
    {
        /// <summary>
        /// Variable del diseñador requerida.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpiar los recursos que se estén utilizando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben eliminar; false en caso contrario, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de Windows Forms

        /// <summary>
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido del método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Text = "Form1";
            this.components = new Container();
            this.label1 = new Label();
            this.button1 = new Button();
            this.textBox1 = new TextBox();
            this.label2 = new Label();
            this.textBox2 = new TextBox();
            this.textBox3 = new TextBox();
            this.textBox4 = new TextBox();
            this.label3 = new Label();
            this.textBox5 = new TextBox();
            this.textBox6 = new TextBox();
            this.label4 = new Label();
            this.textBox7 = new TextBox();
            this.textBox8 = new TextBox();
            this.label5 = new Label();
            this.comboBox1 = new ComboBox();
            this.textBox9 = new TextBox();
            this.label6 = new Label();
            this.textBox13 = new TextBox();
            this.label9 = new Label();
            this.textBox14 = new TextBox();
            this.comboBox3 = new ComboBox();
            this.label10 = new Label();
            this.label11 = new Label();
            this.textBox15 = new TextBox();
            this.textBox16 = new TextBox();
            this.textBox17 = new TextBox();
            this.label12 = new Label();
            this.button2 = new Button();
            this.textBox18 = new TextBox();
            this.label13 = new Label();
            this.label14 = new Label();
            this.textBox19 = new TextBox();
            this.textBox20 = new TextBox();
            this.comboBox5 = new ComboBox();
            this.comboBox6 = new ComboBox();
            this.label15 = new Label();
            this.textBox21 = new TextBox();
            this.label16 = new Label();
            this.label17 = new Label();
            this.label18 = new Label();
            this.label19 = new Label();
            this.label20 = new Label();
            this.textBox22 = new TextBox();
            this.textBox23 = new TextBox();
            this.textBox24 = new TextBox();
            this.textBox25 = new TextBox();
            this.label21 = new Label();
            this.comboBox4 = new ComboBox();
            this.comboBox7 = new ComboBox();
            this.comboBox8 = new ComboBox();
            this.comboBox9 = new ComboBox();
            this.label22 = new Label();
            this.comboBox10 = new ComboBox();
            this.comboBox11 = new ComboBox();
            this.comboBox12 = new ComboBox();
            this.comboBox13 = new ComboBox();
            this.textBox26 = new TextBox();
            this.label23 = new Label();
            this.button3 = new Button();
            this.label24 = new Label();
            this.label25 = new Label();
            this.toolTip1 = new ToolTip(this.components);
            this.toolTip2 = new ToolTip(this.components);
            this.label26 = new Label();
            this.textBox27 = new TextBox();
            this.textBox28 = new TextBox();
            this.textBox29 = new TextBox();
            this.textBox30 = new TextBox();
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.tabPage2 = new TabPage();
            this.tabPage3 = new TabPage();
            this.tabPage4 = new TabPage();
            this.tabPage5 = new TabPage();
            this.button4 = new Button();
            this.textBox12 = new TextBox();
            this.comboBox14 = new ComboBox();
            this.label29 = new Label();
            this.textBox11 = new TextBox();
            this.label28 = new Label();
            this.label27 = new Label();
            this.textBox10 = new TextBox();
            this.label8 = new Label();
            this.label7 = new Label();
            this.toolTip3 = new ToolTip(this.components);
            this.toolTip4 = new ToolTip(this.components);
            this.toolTip5 = new ToolTip(this.components);
            this.toolTip6 = new ToolTip(this.components);
            this.toolTip7 = new ToolTip(this.components);
            this.toolTip8 = new ToolTip(this.components);
            this.toolTip9 = new ToolTip(this.components);
            this.toolTip10 = new ToolTip(this.components);
            this.toolTip11 = new ToolTip(this.components);
            this.toolTip12 = new ToolTip(this.components);
            this.toolTip13 = new ToolTip(this.components);
            this.toolTip14 = new ToolTip(this.components);
            this.toolTip15 = new ToolTip(this.components);
            this.toolTip16 = new ToolTip(this.components);
            this.toolTip17 = new ToolTip(this.components);
            this.toolTip18 = new ToolTip(this.components);
            this.toolTip19 = new ToolTip(this.components);
            this.toolTip20 = new ToolTip(this.components);
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tabPage5.SuspendLayout();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label1.Location = new Point(0x1b, 0x27);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x61, 0x12);
            this.label1.TabIndex = 0;
            this.label1.Text = "Npc Name";
            this.button1.Location = new Point(0x12b, 0x11c);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x6d, 0x17);
            this.button1.TabIndex = 1;
            this.button1.Text = "Add";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.textBox1.Location = new Point(0x8f, 40);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0x77, 20);
            this.textBox1.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label2.Location = new Point(0x1b, 0x52);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x5d, 0x12);
            this.label2.TabIndex = 3;
            this.label2.Text = "Npc Entry";
            this.textBox2.Location = new Point(0x8f, 0x53);
            this.textBox2.MaxLength = 5;
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(0x77, 20);
            this.textBox2.TabIndex = 4;
            this.textBox2.TextAlign = HorizontalAlignment.Center;
            this.textBox3.Location = new Point(0x4e, 0xfb);
            this.textBox3.MaxLength = 5;
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new Size(100, 20);
            this.textBox3.TabIndex = 5;
            this.textBox3.TextAlign = HorizontalAlignment.Center;
            this.textBox4.Location = new Point(0x4e, 0x25);
            this.textBox4.Multiline = true;
            this.textBox4.Name = "textBox4";
            this.textBox4.ReadOnly = true;
            this.textBox4.Size = new Size(100, 0xce);
            this.textBox4.TabIndex = 6;
            this.textBox4.TextAlign = HorizontalAlignment.Center;
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(0x57, 0x10);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x4b, 0x12);
            this.label3.TabIndex = 7;
            this.label3.Text = "Spell ID";
            this.textBox5.Location = new Point(0xe3, 0x25);
            this.textBox5.Multiline = true;
            this.textBox5.Name = "textBox5";
            this.textBox5.ReadOnly = true;
            this.textBox5.Size = new Size(0x2c, 0xce);
            this.textBox5.TabIndex = 8;
            this.textBox5.TextAlign = HorizontalAlignment.Center;
            this.textBox6.Location = new Point(0xe3, 0xf9);
            this.textBox6.MaxLength = 3;
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new Size(0x2c, 20);
            this.textBox6.TabIndex = 9;
            this.textBox6.TextAlign = HorizontalAlignment.Center;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label4.Location = new Point(0xe0, 15);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x7c, 0x12);
            this.label4.TabIndex = 10;
            this.label4.Text = "Casted Every";
            this.textBox7.Location = new Point(0x12b, 0x24);
            this.textBox7.Multiline = true;
            this.textBox7.Name = "textBox7";
            this.textBox7.ReadOnly = true;
            this.textBox7.Size = new Size(0x2c, 0xce);
            this.textBox7.TabIndex = 11;
            this.textBox7.TextAlign = HorizontalAlignment.Center;
            this.textBox8.Location = new Point(0x12b, 0xf9);
            this.textBox8.MaxLength = 3;
            this.textBox8.Name = "textBox8";
            this.textBox8.Size = new Size(0x2c, 20);
            this.textBox8.TabIndex = 12;
            this.textBox8.TextAlign = HorizontalAlignment.Center;
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(0x115, 0xfb);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x10, 0x12);
            this.label5.TabIndex = 13;
            this.label5.Text = "-";
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] { "Main Tank", "Self", "Random" });
            this.comboBox1.Location = new Point(0x17e, 0xf8);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(0x79, 0x15);
            this.comboBox1.TabIndex = 14;
            this.textBox9.Location = new Point(0x17e, 0x24);
            this.textBox9.Multiline = true;
            this.textBox9.Name = "textBox9";
            this.textBox9.ReadOnly = true;
            this.textBox9.Size = new Size(0x77, 0xce);
            this.textBox9.TabIndex = 15;
            this.textBox9.TextAlign = HorizontalAlignment.Center;
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(0x196, 15);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x44, 0x12);
            this.label6.TabIndex = 0x10;
            this.label6.Text = "Target";
            this.textBox13.Location = new Point(0x2a, 0x44);
            this.textBox13.Multiline = true;
            this.textBox13.Name = "textBox13";
            this.textBox13.ReadOnly = true;
            this.textBox13.Size = new Size(0x2c, 0x71);
            this.textBox13.TabIndex = 0x17;
            this.textBox13.TextAlign = HorizontalAlignment.Center;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(0x15, 0x2f);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x58, 0x12);
            this.label9.TabIndex = 0x18;
            this.label9.Text = "Phase ID";
            this.textBox14.Location = new Point(0x73, 0x45);
            this.textBox14.Multiline = true;
            this.textBox14.Name = "textBox14";
            this.textBox14.ReadOnly = true;
            this.textBox14.Size = new Size(0x79, 0x71);
            this.textBox14.TabIndex = 0x19;
            this.textBox14.TextAlign = HorizontalAlignment.Center;
            this.comboBox3.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.Items.AddRange(new object[] { "Health", "Timer" });
            this.comboBox3.Location = new Point(0x73, 190);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new Size(0x79, 0x15);
            this.comboBox3.TabIndex = 0x1b;
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(0x81, 0x30);
            this.label10.Name = "label10";
            this.label10.Size = new Size(90, 0x12);
            this.label10.TabIndex = 0x1c;
            this.label10.Text = "Condition";
            this.label11.AutoSize = true;
            this.label11.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label11.Location = new Point(0xf2, 0x2f);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x8b, 0x12);
            this.label11.TabIndex = 0x1d;
            this.label11.Text = "Timer/Percent";
            this.textBox15.Location = new Point(0x119, 0x44);
            this.textBox15.Multiline = true;
            this.textBox15.Name = "textBox15";
            this.textBox15.ReadOnly = true;
            this.textBox15.Size = new Size(0x2c, 0x71);
            this.textBox15.TabIndex = 30;
            this.textBox15.TextAlign = HorizontalAlignment.Center;
            this.textBox16.Location = new Point(0x119, 190);
            this.textBox16.MaxLength = 3;
            this.textBox16.Name = "textBox16";
            this.textBox16.Size = new Size(0x2c, 20);
            this.textBox16.TabIndex = 0x1f;
            this.textBox16.TextAlign = HorizontalAlignment.Center;
            this.textBox17.Location = new Point(0x222, 0x24);
            this.textBox17.Multiline = true;
            this.textBox17.Name = "textBox17";
            this.textBox17.ReadOnly = true;
            this.textBox17.Size = new Size(0x2c, 0xce);
            this.textBox17.TabIndex = 0x20;
            this.textBox17.TextAlign = HorizontalAlignment.Center;
            this.label12.AutoSize = true;
            this.label12.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label12.Location = new Point(0x214, 15);
            this.label12.Name = "label12";
            this.label12.Size = new Size(80, 0x12);
            this.label12.TabIndex = 0x22;
            this.label12.Text = "Phase #";
            this.button2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.button2.Location = new Point(0x12b, 0xf8);
            this.button2.Name = "button2";
            this.button2.Size = new Size(0x6d, 0x17);
            this.button2.TabIndex = 0x23;
            this.button2.Text = "Add";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new EventHandler(this.button2_Click);
            this.textBox18.Location = new Point(0x183, 0x44);
            this.textBox18.Multiline = true;
            this.textBox18.Name = "textBox18";
            this.textBox18.ReadOnly = true;
            this.textBox18.Size = new Size(0x77, 0x71);
            this.textBox18.TabIndex = 0x24;
            this.textBox18.TextAlign = HorizontalAlignment.Center;
            this.textBox18.WordWrap = false;
            this.label13.AutoSize = true;
            this.label13.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label13.Location = new Point(0x1a5, 0x2f);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x31, 0x12);
            this.label13.TabIndex = 0x25;
            this.label13.Text = "Text";
            this.label14.AutoSize = true;
            this.label14.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label14.Location = new Point(0x22c, 0x30);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x62, 0x12);
            this.label14.TabIndex = 0x26;
            this.label14.Text = "Chat Type";
            this.textBox19.Location = new Point(0x183, 0xbd);
            this.textBox19.Name = "textBox19";
            this.textBox19.Size = new Size(0x77, 20);
            this.textBox19.TabIndex = 0x27;
            this.textBox20.Location = new Point(0x220, 0x44);
            this.textBox20.Multiline = true;
            this.textBox20.Name = "textBox20";
            this.textBox20.ReadOnly = true;
            this.textBox20.Size = new Size(0x79, 0x71);
            this.textBox20.TabIndex = 40;
            this.textBox20.TextAlign = HorizontalAlignment.Center;
            this.comboBox5.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox5.FormattingEnabled = true;
            this.comboBox5.Items.AddRange(new object[] { "Emote", "Say", "Yell" });
            this.comboBox5.Location = new Point(0x220, 0xbd);
            this.comboBox5.Name = "comboBox5";
            this.comboBox5.Size = new Size(0x79, 0x15);
            this.comboBox5.TabIndex = 0x29;
            this.comboBox6.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox6.FormattingEnabled = true;
            this.comboBox6.Items.AddRange(new object[] { "True", "False" });
            this.comboBox6.Location = new Point(0x8f, 130);
            this.comboBox6.Name = "comboBox6";
            this.comboBox6.Size = new Size(0x54, 0x15);
            this.comboBox6.TabIndex = 0x2a;
            this.comboBox6.SelectedItem = "True";
            this.label15.AutoSize = true;
            this.label15.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label15.Location = new Point(30, 0x81);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x5e, 0x12);
            this.label15.TabIndex = 0x2b;
            this.label15.Text = "Can Move";
            this.textBox21.Location = new Point(0x222, 0xf8);
            this.textBox21.MaxLength = 3;
            this.textBox21.Name = "textBox21";
            this.textBox21.Size = new Size(0x2c, 20);
            this.textBox21.TabIndex = 0x2c;
            this.textBox21.TextAlign = HorizontalAlignment.Center;
            this.label16.AutoSize = true;
            this.label16.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label16.Location = new Point(0x4b, 0x88);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x3d, 0x12);
            this.label16.TabIndex = 0x2d;
            this.label16.Text = "Aggro";
            this.label17.AutoSize = true;
            this.label17.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label17.Location = new Point(0x15, 0xac);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x73, 0x12);
            this.label17.TabIndex = 0x2e;
            this.label17.Text = "Killed Player";
            this.label18.AutoSize = true;
            this.label18.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label18.Location = new Point(0x4b, 0xd0);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x3d, 0x12);
            this.label18.TabIndex = 0x2f;
            this.label18.Text = "Death";
            this.label19.AutoSize = true;
            this.label19.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label19.Location = new Point(0x15, 0x65);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x47, 0x12);
            this.label19.TabIndex = 0x30;
            this.label19.Text = "Enrage";
            this.label20.AutoSize = true;
            this.label20.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label20.Location = new Point(0xab, 0x4c);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x4b, 0x12);
            this.label20.TabIndex = 0x31;
            this.label20.Text = "Spell ID";
            this.textBox22.Location = new Point(0x9e, 0x66);
            this.textBox22.MaxLength = 5;
            this.textBox22.Name = "textBox22";
            this.textBox22.Size = new Size(100, 20);
            this.textBox22.TabIndex = 50;
            this.textBox22.TextAlign = HorizontalAlignment.Center;
            this.textBox23.Location = new Point(0x9e, 0x89);
            this.textBox23.MaxLength = 5;
            this.textBox23.Name = "textBox23";
            this.textBox23.Size = new Size(100, 20);
            this.textBox23.TabIndex = 0x33;
            this.textBox23.TextAlign = HorizontalAlignment.Center;
            this.textBox24.Location = new Point(0x9e, 0xad);
            this.textBox24.MaxLength = 5;
            this.textBox24.Name = "textBox24";
            this.textBox24.Size = new Size(100, 20);
            this.textBox24.TabIndex = 0x34;
            this.textBox24.TextAlign = HorizontalAlignment.Center;
            this.textBox25.Location = new Point(0x9e, 0xd1);
            this.textBox25.MaxLength = 5;
            this.textBox25.Name = "textBox25";
            this.textBox25.Size = new Size(100, 20);
            this.textBox25.TabIndex = 0x35;
            this.textBox25.TextAlign = HorizontalAlignment.Center;
            this.label21.AutoSize = true;
            this.label21.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label21.Location = new Point(0x12b, 0x4c);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x44, 0x12);
            this.label21.TabIndex = 0x36;
            this.label21.Text = "Target";
            this.comboBox4.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox4.FormattingEnabled = true;
            this.comboBox4.Items.AddRange(new object[] { "Main Tank", "Self", "Random" });
            this.comboBox4.Location = new Point(0x112, 0x66);
            this.comboBox4.Name = "comboBox4";
            this.comboBox4.Size = new Size(0x79, 0x15);
            this.comboBox4.TabIndex = 0x37;
            this.comboBox7.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox7.FormattingEnabled = true;
            this.comboBox7.Items.AddRange(new object[] { "Main Tank", "Self", "Random" });
            this.comboBox7.Location = new Point(0x112, 0x89);
            this.comboBox7.Name = "comboBox7";
            this.comboBox7.Size = new Size(0x79, 0x15);
            this.comboBox7.TabIndex = 0x38;
            this.comboBox8.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox8.FormattingEnabled = true;
            this.comboBox8.Items.AddRange(new object[] { "Main Tank", "Self", "Random" });
            this.comboBox8.Location = new Point(0x112, 0xad);
            this.comboBox8.Name = "comboBox8";
            this.comboBox8.Size = new Size(0x79, 0x15);
            this.comboBox8.TabIndex = 0x39;
            this.comboBox9.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox9.FormattingEnabled = true;
            this.comboBox9.Items.AddRange(new object[] { "Main Tank", "Self", "Random" });
            this.comboBox9.Location = new Point(0x112, 0xd1);
            this.comboBox9.Name = "comboBox9";
            this.comboBox9.Size = new Size(0x79, 0x15);
            this.comboBox9.TabIndex = 0x3a;
            this.label22.AutoSize = true;
            this.label22.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label22.Location = new Point(550, 0x4c);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x62, 0x12);
            this.label22.TabIndex = 0x3b;
            this.label22.Text = "Chat Type";
            this.comboBox10.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox10.FormattingEnabled = true;
            this.comboBox10.Items.AddRange(new object[] { "Emote", "Say", "Yell" });
            this.comboBox10.Location = new Point(0x218, 0x66);
            this.comboBox10.Name = "comboBox10";
            this.comboBox10.Size = new Size(0x79, 0x15);
            this.comboBox10.TabIndex = 60;
            this.comboBox11.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox11.FormattingEnabled = true;
            this.comboBox11.Items.AddRange(new object[] { "Emote", "Say", "Yell" });
            this.comboBox11.Location = new Point(0x218, 0x8a);
            this.comboBox11.Name = "comboBox11";
            this.comboBox11.Size = new Size(0x79, 0x15);
            this.comboBox11.TabIndex = 0x3d;
            this.comboBox12.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox12.FormattingEnabled = true;
            this.comboBox12.Items.AddRange(new object[] { "Emote", "Say", "Yell" });
            this.comboBox12.Location = new Point(0x218, 0xae);
            this.comboBox12.Name = "comboBox12";
            this.comboBox12.Size = new Size(0x79, 0x15);
            this.comboBox12.TabIndex = 0x3e;
            this.comboBox13.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox13.FormattingEnabled = true;
            this.comboBox13.Items.AddRange(new object[] { "Emote", "Say", "Yell" });
            this.comboBox13.Location = new Point(0x218, 210);
            this.comboBox13.Name = "comboBox13";
            this.comboBox13.Size = new Size(0x79, 0x15);
            this.comboBox13.TabIndex = 0x3f;
            this.textBox26.Location = new Point(100, 0x66);
            this.textBox26.MaxLength = 2;
            this.textBox26.Name = "textBox26";
            this.textBox26.Size = new Size(0x2c, 20);
            this.textBox26.TabIndex = 0x40;
            this.textBox26.TextAlign = HorizontalAlignment.Center;
            this.label23.AutoSize = true;
            this.label23.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label23.Location = new Point(0x6c, 0x51);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x1c, 0x12);
            this.label23.TabIndex = 0x41;
            this.label23.Text = "%";
            this.button3.Location = new Point(0x142, 0x1be);
            this.button3.Name = "button3";
            this.button3.Size = new Size(0x6d, 0x22);
            this.button3.TabIndex = 0x42;
            this.button3.Text = "Create!";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new EventHandler(this.button3_Click);
            this.label24.AutoSize = true;
            this.label24.Font = new Font("Segoe Print", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label24.Location = new Point(0x256, 0x1c4);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x6d, 0x1c);
            this.label24.TabIndex = 0x43;
            this.label24.Text = "By Maczuga";
            this.label25.AutoSize = true;
            this.label25.Font = new Font("Segoe Print", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label25.Location = new Point(0x27, 0x1c4);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x69, 0x1c);
            this.label25.TabIndex = 0x44;
            this.label25.Text = "Version 1.0";
            this.label26.AutoSize = true;
            this.label26.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label26.Location = new Point(0x1ba, 0x4d);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x31, 0x12);
            this.label26.TabIndex = 0x45;
            this.label26.Text = "Text";
            this.textBox27.Location = new Point(0x198, 0x67);
            this.textBox27.Name = "textBox27";
            this.textBox27.Size = new Size(0x77, 20);
            this.textBox27.TabIndex = 70;
            this.textBox28.Location = new Point(0x198, 0x8a);
            this.textBox28.Name = "textBox28";
            this.textBox28.Size = new Size(0x77, 20);
            this.textBox28.TabIndex = 0x47;
            this.textBox29.Location = new Point(0x198, 0xae);
            this.textBox29.Name = "textBox29";
            this.textBox29.Size = new Size(0x77, 20);
            this.textBox29.TabIndex = 0x48;
            this.textBox30.Location = new Point(0x198, 210);
            this.textBox30.Name = "textBox30";
            this.textBox30.Size = new Size(0x77, 20);
            this.textBox30.TabIndex = 0x49;
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Controls.Add(this.tabPage5);
            this.tabControl1.Location = new Point(0x10, 0x48);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x2c4, 0x153);
            this.tabControl1.TabIndex = 0x4a;
            this.tabPage1.BackColor = Color.Transparent;
            this.tabPage1.Controls.Add(this.textBox13);
            this.tabPage1.Controls.Add(this.label9);
            this.tabPage1.Controls.Add(this.textBox14);
            this.tabPage1.Controls.Add(this.label10);
            this.tabPage1.Controls.Add(this.textBox15);
            this.tabPage1.Controls.Add(this.label11);
            this.tabPage1.Controls.Add(this.textBox18);
            this.tabPage1.Controls.Add(this.label13);
            this.tabPage1.Controls.Add(this.textBox20);
            this.tabPage1.Controls.Add(this.label14);
            this.tabPage1.Controls.Add(this.comboBox3);
            this.tabPage1.Controls.Add(this.textBox16);
            this.tabPage1.Controls.Add(this.textBox19);
            this.tabPage1.Controls.Add(this.comboBox5);
            this.tabPage1.Controls.Add(this.button2);
            this.tabPage1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tabPage1.Location = new Point(4, 0x16);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(700, 0x139);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Phases";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage2.BackColor = Color.Transparent;
            this.tabPage2.Controls.Add(this.textBox4);
            this.tabPage2.Controls.Add(this.textBox5);
            this.tabPage2.Controls.Add(this.textBox7);
            this.tabPage2.Controls.Add(this.textBox9);
            this.tabPage2.Controls.Add(this.textBox17);
            this.tabPage2.Controls.Add(this.label3);
            this.tabPage2.Controls.Add(this.label4);
            this.tabPage2.Controls.Add(this.label6);
            this.tabPage2.Controls.Add(this.label12);
            this.tabPage2.Controls.Add(this.textBox3);
            this.tabPage2.Controls.Add(this.textBox6);
            this.tabPage2.Controls.Add(this.textBox8);
            this.tabPage2.Controls.Add(this.label5);
            this.tabPage2.Controls.Add(this.comboBox1);
            this.tabPage2.Controls.Add(this.textBox21);
            this.tabPage2.Controls.Add(this.button1);
            this.tabPage2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tabPage2.Location = new Point(4, 0x16);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(700, 0x139);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Spells";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.tabPage3.Controls.Add(this.label19);
            this.tabPage3.Controls.Add(this.textBox30);
            this.tabPage3.Controls.Add(this.label23);
            this.tabPage3.Controls.Add(this.textBox29);
            this.tabPage3.Controls.Add(this.comboBox13);
            this.tabPage3.Controls.Add(this.textBox26);
            this.tabPage3.Controls.Add(this.textBox28);
            this.tabPage3.Controls.Add(this.label20);
            this.tabPage3.Controls.Add(this.comboBox9);
            this.tabPage3.Controls.Add(this.comboBox12);
            this.tabPage3.Controls.Add(this.textBox25);
            this.tabPage3.Controls.Add(this.textBox27);
            this.tabPage3.Controls.Add(this.label18);
            this.tabPage3.Controls.Add(this.textBox22);
            this.tabPage3.Controls.Add(this.label26);
            this.tabPage3.Controls.Add(this.comboBox11);
            this.tabPage3.Controls.Add(this.comboBox8);
            this.tabPage3.Controls.Add(this.label21);
            this.tabPage3.Controls.Add(this.comboBox4);
            this.tabPage3.Controls.Add(this.textBox24);
            this.tabPage3.Controls.Add(this.label22);
            this.tabPage3.Controls.Add(this.comboBox10);
            this.tabPage3.Controls.Add(this.label17);
            this.tabPage3.Controls.Add(this.label16);
            this.tabPage3.Controls.Add(this.comboBox7);
            this.tabPage3.Controls.Add(this.textBox23);
            this.tabPage3.Location = new Point(4, 0x16);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Size = new Size(700, 0x139);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Events";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.tabPage4.Controls.Add(this.button4);
            this.tabPage4.Controls.Add(this.textBox12);
            this.tabPage4.Controls.Add(this.comboBox14);
            this.tabPage4.Controls.Add(this.label29);
            this.tabPage4.Controls.Add(this.textBox11);
            this.tabPage4.Controls.Add(this.label28);
            this.tabPage4.Controls.Add(this.label27);
            this.tabPage4.Controls.Add(this.textBox10);
            this.tabPage4.Controls.Add(this.label8);
            this.tabPage4.Controls.Add(this.comboBox6);
            this.tabPage4.Controls.Add(this.label15);
            this.tabPage4.Controls.Add(this.label2);
            this.tabPage4.Controls.Add(this.label1);
            this.tabPage4.Controls.Add(this.textBox2);
            this.tabPage4.Controls.Add(this.textBox1);
            this.tabPage4.ForeColor = SystemColors.ControlText;
            this.tabPage4.Location = new Point(4, 0x16);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Size = new Size(700, 0x139);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "Main";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.button4.Location = new Point(0x1b1, 0xef);
            this.button4.Name = "button4";
            this.button4.Size = new Size(0x6d, 0x17);
            this.button4.TabIndex = 0x37;
            this.button4.Text = "Add";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new EventHandler(this.button4_Click_1);
            /*this.tabPage5.Controls.Add(this.button4);
            this.tabPage5.Controls.Add(this.textBox12);
            this.tabPage5.Controls.Add(this.comboBox14);
            this.tabPage5.Controls.Add(this.label29);
            this.tabPage5.Controls.Add(this.textBox11);
            this.tabPage5.Controls.Add(this.label28);
            this.tabPage5.Controls.Add(this.label27);
            this.tabPage5.Controls.Add(this.textBox10);
            this.tabPage5.Controls.Add(this.label8);
            this.tabPage5.Controls.Add(this.comboBox6);
            this.tabPage5.Controls.Add(this.label15);
            this.tabPage5.Controls.Add(this.label2);
            this.tabPage5.Controls.Add(this.label1);
            this.tabPage5.Controls.Add(this.textBox2);
            this.tabPage5.Controls.Add(this.textBox1);*/
            this.tabPage5.ForeColor = SystemColors.ControlText;
            this.tabPage5.Location = new Point(4, 0x16);
            this.tabPage5.Name = "tabPage5";
            this.tabPage5.Size = new Size(700, 0x139);
            this.tabPage5.TabIndex = 4;
            this.tabPage5.Text = "Smth";
            this.tabPage5.UseVisualStyleBackColor = true;
            this.textBox12.Location = new Point(350, 190);
            this.textBox12.MaxLength = 5;
            this.textBox12.Name = "textBox12";
            this.textBox12.Size = new Size(0x77, 20);
            this.textBox12.TabIndex = 0x36;
            this.textBox12.TextAlign = HorizontalAlignment.Center;
            this.comboBox14.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox14.FormattingEnabled = true;
            this.comboBox14.Items.AddRange(new object[] { "Arcane", "Shadow", "Frost", "Fire", "Nature", "Holy", "Physical" });
            this.comboBox14.Location = new Point(0x200, 0xbd);
            this.comboBox14.Name = "comboBox14";
            this.comboBox14.Size = new Size(0x79, 0x15);
            this.comboBox14.TabIndex = 0x35;
            this.label29.AutoSize = true;
            this.label29.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label29.Location = new Point(0x1fd, 0x31);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x6f, 0x12);
            this.label29.TabIndex = 0x34;
            this.label29.Text = "Spell School";
            this.textBox11.Location = new Point(0x200, 70);
            this.textBox11.Multiline = true;
            this.textBox11.Name = "textBox11";
            this.textBox11.ReadOnly = true;
            this.textBox11.Size = new Size(0x79, 0x71);
            this.textBox11.TabIndex = 0x33;
            this.textBox11.TextAlign = HorizontalAlignment.Center;
            this.label28.AutoSize = true;
            this.label28.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label28.Location = new Point(0x171, 0x31);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x4b, 0x12);
            this.label28.TabIndex = 50;
            this.label28.Text = "Spell ID";
            this.label27.AutoSize = true;
            this.label27.Font = new Font("Verdana", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label27.Location = new Point(430, 13);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x97, 0x12);
            this.label27.TabIndex = 0x2f;
            this.label27.Text = "Spell Immunities";
            this.textBox10.Location = new Point(0x15c, 70);
            this.textBox10.Multiline = true;
            this.textBox10.Name = "textBox10";
            this.textBox10.ReadOnly = true;
            this.textBox10.Size = new Size(0x79, 0x71);
            this.textBox10.TabIndex = 0x2e;
            this.textBox10.TextAlign = HorizontalAlignment.Center;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Times New Roman", 24f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label7.Location = new Point(0x94, 9);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x1d7, 0x24);
            this.label7.TabIndex = 0x4b;
            this.label7.Text = "CataProject Script Generator";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            //base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = SystemColors.ControlLight;
            base.ClientSize = new Size(0x2ea, 0x1ee);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.tabControl1);
            base.Controls.Add(this.label25);
            base.Controls.Add(this.label24);
            base.Controls.Add(this.button3);
            //base.FormBorderStyle = FormBorderStyle.Fixed3D;
            base.Name = "Form1";
            this.Text = "CataProject Script Generator";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.tabPage4.ResumeLayout(false);
            this.tabPage4.PerformLayout();
            this.tabPage5.ResumeLayout(false);
            this.tabPage5.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion
    }
}

